In [18]:
import numpy as np
matrix1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrix2 = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0],[10.0,11.0,12.0]])
print("matrix1's shape",matrix1.shape)
print("matrix2's shape",matrix2.shape)
print('-------------------')
print("matrix1's dimension",matrix1.ndim)
print("matrix2's dimension",matrix2.ndim)
print('-------------------')
print("matrix1's data type",matrix1.dtype)
print("matrix2's data type",matrix2.dtype)
print('-------------------')
print("matrix1's size:",matrix1.size)
print("matrix2's size:",matrix1.size)
print('-------------------')
print(matrix1.reshape(2,6))
print(matrix2.reshape(12,))

matrix1's shape (12,)
matrix2's shape (4, 3)
-------------------
matrix1's dimension 1
matrix2's dimension 2
-------------------
matrix1's data type int32
matrix2's data type float64
-------------------
matrix1's size: 12
matrix2's size: 12
-------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.]


In [20]:
import numpy as np
matrix3 = np.zeros((3,4))
print(matrix3)
print('-------------------')
matrix4 = np.ones((3,4))
print(matrix4)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
-------------------
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [38]:
import numpy as np
a = np.array([5,10,15,20],dtype = float)
b = np.array([1,2,6,4],dtype = float)
print(a,b)
print(a-b,a+b,a*b,a/b)
print(a<16)

[  5.  10.  15.  20.] [ 1.  2.  6.  4.]
[  4.   8.   9.  16.] [  6.  12.  21.  24.] [  5.  20.  90.  80.] [ 5.   5.   2.5  5. ]
[ True  True  True False]


In [ ]:
for more application, please refer to 
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html